### ISSUE TITLE
[please fix] Picking up the Townhall block to move the colony equals FAIL

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#110]
Went to move my colony from minecolonies and it said i needed to abandon or delete my colony upon deletion i can not place a town hall. this is stopping me from claiming and protecting my items.

**To Reproduce**
1. start a colony
2. build it up a bit
3. remove townhall block
4. place in new area
5. click delete colony
6. try placing townhall block after a while
7. townhall block placed and puff gone
8. relog and like magic its back in inventory 

**Versions:**
 - Minecraft: 1.12
 - Forge: 14.23.5.2823
 - Mod Pack: World of dragons V:14.38.170
 - Mod Name: minecolonies
 - Mod Version: 1.12.2-0.10.236-ALPHA

**Comment by kreezxil** [comment]
for now I think you were simply suppose to craft a new townhall block and place it. Just the same I'll make sure the Minecolonies devs have a copy of this.

**Comment by kreezxil** [comment]
The developer says you are suppose to be able to move the townhall block that you have built. In fact he said this is the correct behavior for when you place the townhall block down and it is inside the pad buffer to the next colony. I have this set to 10 chunks which is 160 blocks. Therefore if your townhall block is within 160 blocks of a colony it'll disappear and go back to your inventory, but because it happens server side only it appears to disappear and if you relog there it is. I've suggested that the townhall block needs to be a bit more verbose with it's messages when you try to move it and some other mechanic needs to happen to prevent it from looking like it disappears.

So my theory is that you tried to move your townhall bock to just outside your existing border, which as far as the block was concerned is within the padding and therefore you aren't allowed to do it. You will have to move the block 160 blocks away from the edger of you existing colony to succeed in moving it.

**Comment by kreezxil** [comment]
I'm closing this as a proper reason was given as to why it happened by the developer, it's technically not fixed in a way that doesn't cause confusion. But at least you get the townhall back so you can place it further out. The bug is at the Minecolonies tracker and is open there.
