### ISSUE TITLE
Minecolonies commands not working correctly

### ISSUE THREAD

**Issue by Caeasarus** [kreezxil/World-of-Dragons#114]
**Describe the bug**
When you want to use a Minecolonies command, the "colony" parameter is not recognized, but needed

**To Reproduce**
1. Start a world (with command power)
2. Have a Minecolonies Colony
3. Type a command like /mc colony claim (not fitting with /mc_old)
4. Fit possible Parameters (like 1 0 10 true) 
5. See error about "colonies parameter required"

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2824
 - Mod Pack : World of Dragons 14.39.171
 - Mod Name: Minecolonies
 - Mod Version: 1.12.2-0.10.239-BETA

**Comment by kreezxil** [comment]
That's correct it's telling you the right thing because you are leaving
information out and you don't understand how they designed the command to
be used.

The options for the command you gave as an example appear like this:

**/mineColonies colony claim <colony: #> <dimension: #> [range: #] [add:
t/f]**

The stuff in <> is required, the stuff in [] is option, of this much I am
assure you have rightly discerned.

However, what you do not know is that Minecolonies uses argument naming,
which is an odd convention to say the least, I have had discussions with
the developers about it.

Therefore given your data please use:

**/mc colony claim colony: 1 dimension: 0 range: 10 add: true**

at which point you'll discover the command actually does work. If you would
like to file a formal complaint with the minecolonies team feel free to do
so at https://github.com/ldtteam/minecolonies

>
