### ISSUE TITLE
[please fix] Crash Using Tiny Mob Farms

### ISSUE THREAD

**Issue by Th3GreenGamer** [kreezxil/World-of-Dragons#139]
**Describe the bug**
When the timer is up in the Stone Mob Farm from Tiny Mob Farms with a vanilla cow lasso inside it, I crash. I was in the gui at the tine.

**To Reproduce**
1. Put vanilla cow lasso inside stone mob farm
2. Use gui
3. Wait for timer

**Screenshots**
"The game crashed whilst rendering screen
Error: java.lang.ArrayIndexOutOfBoundsException: 21"
See attachment for further crash report.
**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2825
 - Mod Pack : WOD 14.42.174
 - Mod Name: Tiny Mob Farms
 - Mod Version: 1.0.5

**Additional context**
Nope

https://pastebin.com/qh4VK9cg

**Comment by kreezxil** [comment]
reported at https://minecraft.curseforge.com/projects/tiny-mob-farm?comment=60

**Comment by kreezxil** [comment]
The author has responded that he can't fix it and said this is actually an Ice and Fire issue. https://minecraft.curseforge.com/projects/tiny-mob-farm?comment=61

I'll now see what I can do in that department.

**Comment by davidmaamoaix** [comment]
Hmm...
I checked the crash log again. Judging from the log, the error is not caused by "timer finished", but rather the drawing tooltip of certain ItemStack.
This should not be particularly caused by Tiny Mob Farm because the method causing the error (GuiContainer#renderHoveredToolTip) is used by most GUIs, including vanilla ones.
Therefore, I am wondering if you remember what item your mouse is hovering on when you experienced the crash.

(Note: I think Ice and Fire has updated in the past few days, and EnumBestiaryPages#containedPages is changed/removed. Try updating Ice and Fire and see if the error persist.)

**Comment by davidmaamoaix** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/blob/1574f6430a9bd20df616da7c3d1a319a73d5259b/src/main/java/com/github/alexthe666/iceandfire/item/ItemBestiary.java#L77-L84
ItemBestiary's addTooltip method reference the index of an enum based on the NBT of the stack; unfortunately, the NBT contains unexpected values and referenced an index that is not in the enum.

I am assuming that this is caused by updating Ice and Fire; the previous version had the entry in the enum, while the newer version does not have the entry in the enum. If this is the case, I would suggest to destroy the ItemStack that causes the error when hovering on it (chuck it into lava or something; just do not hover your mouse over it in a GUI).

**Comment by kreezxil** [comment]
interesting
