### ISSUE TITLE
Major dropdown in performance

### ISSUE THREAD

**Issue by megadeth116** [kreezxil/World-of-Dragons#176]
The issue occurs on version 14.61.193
Performance dropped so much I can't even open up the pack. On the previous update I've used 5GB ram to play and it was plenty and now with 5GB the game doesn't even load up (other programes like steam and google chrome are closed).

**Comment by kreezxil** [comment]
it would help if you sent me a your dxdiag information. If you don't know
how to get it.

right click on start and then hit run and type dxdiag and then hit ok.

export or otherwise save the result and send it to me in this thread.

Also start the pack and with it at the main menu screen with dragon icon on
it, open up your taskmanager and send me a screenshot of that in details
view.

Now enter video options under options and change all the settings to potato
class. ie no fancy graphics, mipmap 0, view distance 5, etc. We're trying
to enter the pack here. Once it is open hold both the F3 and the 'c' key
simultaneously for 10 seconds or longer as this will force a crash. Get the
link and send me the crash report also here.

and maybe this should've been first, but if you've installed optifine,
remove it.

**Comment by megadeth116** [comment]
I might've been inaccurate. I can't actually load the pack, It gets stuck on 6/7 of mods inizialization (then I'm out of RAM). I didn't modified the pack in any way, so there's no optifine etc.
pastebin link: https://pastebin.com/HV5nBP4w

**Comment by kreezxil** [comment]
Here's a step by step with pictures showing you how to increase the ram
settings on a pack by pack basis.
https://github.com/kreezxil/World-of-Dragons/wiki/Assign-More-Ram

**Comment by megadeth116** [comment]
On previous updates with having allocated 5120mb it was using 80-90%, now the usage increased by like gigabyte and in changelog you just added one mod and updated like 3 of them. My my problem is when I check task manager it uses 6,5 gb (all of my ram) when 5gb is allocated, so if I allocated 6gb, it would be the same problem. My question is what's with the ram usage that increrased? this problem isn't only for my. My friend also has the same settings and also can't open up the pack on this update but easily could on previous updates (we've beed playing since 14.57.189 version) If theres no hope then just close this issue.

**Comment by megadeth116** [comment]
I just reverted to previous update (14.61.191) and got this https://imgur.com/a/9lRJiwY on fresh world. After loading the ram stays at 60-85%. I allocated 5120MB ram and this is with programs running in the background.
Don't know if it's relevant but the ram issue starts with initialization on the 6/7 when  one of the JEI pulgins is loading. Then the ram jumps for about 0.5-1GB

**Comment by kreezxil** [comment]
the 6/7 is meaningless to both mod and pack devs.

the minimum requirement for the pack jumped to 6GB with fps stuttering. and the recommended is 8GB. This is due to players constantly wanting new mods.

The new pack **World of Dragons - Medieval Times** does not have this issue and will not be having new mods added to it. I created it because I didn't want wipe existing worlds and goto Major version 15. Medieval Times is what the pack should've been all along.

Give [(Medieval Times)](https://minecraft.curseforge.com/projects/medieval-times) a shot.

**Comment by kreezxil** [comment]
for taskmanager I wanted to see a list of your processes not the meter

this information from the dxdiag tells me your computer is 8gb max current physical memory.

            Memory: 8192MB RAM

You will need to deactivate a bunch of programs to have bare minimum to allow the pack to run. If you don't your computer will attempt to use the swap file to simulate more ram causing the noticed decreased performance.

to keep using the amount of programs you have open while playing minecraft you need a computer that is 12gb or more.

Further your computer is a minimum of 4.5 years old as indicated by this line

               BIOS: BIOS Date: 05/15/15 10:23:00 Ver: 23.03

and as far as gaming rigs go the processor is that great anymore either

          Processor: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 CPUs), ~3.6GHz

The speed is great but the cpu archtecture isn't.

For this pack an i5 would be the minimal architecture and you will need at least  a 2GB video card with 2GB or more of dedicated ddr4 or better video ram.

I have frozen the pack and am taking no more suggestions for it. Which is why I made Medieval Times.

Your computer is already using way too much simulated ram as indicated by this line

          Page File: 4635MB used, 11623MB available

It's normal for an operating system to create a page file of 1.5 times the size of the physical ram. And it's normal for that page file to be used in an office environment. But it's not ideal in a gaming environment, or one where video performance (viewing or rendering) is a must. Minecraft fits in both of these categories.

You do have a good video card, hopefully this is not a laptop so you can get a better motherboard, cpu and more ram. If it's a laptop. ooo boy.

          Card name: NVIDIA GeForce GTX 750 Ti

This is why I think you have a laptop. Is because this particular card of which I have too, it never came with less than 1GB unless it was integrated. 

You have for it, I see it is shared and is one of the reasons your page file is being used.

     Display Memory: 4044 MB (This is a technical lie, it's using 4gb of  your 8gb to emulate it's dedicated ram)
   Dedicated Memory: 972 MB (This is likely true, and based on the next line I can believe it)
      Shared Memory: 3072 MB (The truth then, is it has 1gb of dedicated video ram and it steals 3 gb from your physical ram thus giving you a laptop with 5gb of ram for both windows and java to run in.)

Windows 10 requires 1GB, Windows 7,8, & Vista require 2GB. Best case scenario leaves you with 4GB to run the pack. You were already hurting for the last two months as the pack grew in size. Now you can't even open it because you don't have the needed ram as it is being stolen by applications and this lie from the integrated video card.

If you can adust the amount of shared video ram to 0 you can restore performance because that will give 3GB back to the operating system boosting you from 4GB TO 7GB.

**Comment by megadeth116** [comment]
https://imgur.com/a/1rl4RXu Here are the proceses as you said.
My PC isn't a laptop so I guess is good for me, but unfortunately I won't be upgrading it anytime soon. 
I think it's better for me to buy new one but still that a fair bit of time for that.
I guess it's closed topic then. The mystery of +1Gb after adding one mod will still remain a secret for me (even if you already may have told me lol). Thanks for helping me out.

**Comment by kreezxil** [comment]
cyclic is a big mod.

And yet I continue to get recommendations for mods to add.

**Comment by kreezxil** [comment]
I'm removing botania in the next update which should allow you to open the
pack again. that's a big mod that thankfully doesn't add worldgen so other
than machines and items being lost it won't hurt the servers.

I'm removing it because it is easy to exploit and highly server unfriendly.
