### ISSUE TITLE
[don't fix] multimc "unable to resolve some mod ids" (probably a multimc/curseforge issue)

### ISSUE THREAD

**Issue by Xetaxheb** [kreezxil/World-of-Dragons#178]
**Describe the bug**
Pack (14.61.193) fails to install on multimc, 14.59.191 installs properly
"unable to resolve some mod ids"

**To Reproduce**
1. Try to install World+of+Dragons-14.61.193 on multimc

Latest Log: https://gist.github.com/Xetaxheb/82ae5d075b6ac821f5e969b75209bf7a

**Additional context**
This is probably a multimc issue, or some issue with curseforge's backend, but I figured i'd post this here if anyone else has the issue. You can open the zip and text-edit manifest.json to this (then put it back in zip and install): https://gist.githubusercontent.com/Xetaxheb/ebc244863c4a51b9c0d84a920e42930e/raw/301d2209d9b424c6b64d7362feec43998ea0d896/gistfile1.txt
And download+install these jars manually:
https://minecraft.curseforge.com/projects/random-psideas/files/2711623
https://minecraft.curseforge.com/projects/tweakers-construct/files/2711802
https://minecraft.curseforge.com/projects/autoreglib/files/2711582

**Comment by Xetaxheb** [comment]
I've also posted on multimc's github about this, we'll see if it turns out to be a multimc issue (maybe their backend) or curseforge issue or maybe my internet (least likely). It's just a really bizarre issue because normally this happens when a mod author took down an old file but this doesn't appear to be the case here, and I can download them manually just fine.

**Comment by Xetaxheb** [comment]
Looks like an issue with the cursemeta backend.

**Comment by kreezxil** [comment]
this issue which happens on Twitch app too, is due to database
synchronicity. When it happens you need to wait at least 2 to 4 hours for
it to resolve. The problem is that CurseForge and Twitch both using a
concept called "shards" to ensure that players around the world receive
content in a sufficiently speedy manner. Therefore when a pack or mod
update is released, those trying to install the pack or mod immediately
will encounter this issue if the database or shard their being forced to
download from has not updated with the new pack or mod data.

**Comment by kreezxil** [comment]
I have a conversation with a Twitch developer that confirms this.
