### ISSUE TITLE
[please add] Colytra

### ISSUE THREAD

**Issue by AceWolf456** [kreezxil/World-of-Dragons#180]
I made a request previously to add a mod for a specific feature, I was mistaken about what mod the feature was in, so I understand if this is declined. 

This mod adds the ability to craft the Elytra into a bauble or attach it to a chestpiece. I think that's everything, it's not big.
Colytra link: https://minecraft.curseforge.com/projects/colytra

**Comment by kreezxil** [comment]
Sorry, not adding anything more to WORLD OF DRAGONS. It's too big, already
requires 6 GB to run with client side stutter and 8GB to run with no client
side stutter. This means it is already at the size where a basic gaming rig
is required. A machine with a minimum of 8GB on board with 6GB minimum
assigned to the pack for stutter. To achieve 8GB you will need a machine
with 12GB or more which is standard gaming rig. And for top performance an
advanced gaming rig which is one with 16GB plus.

I've added too many player recommended mods which is why we're in this
state now. Feel free to add that mod to your copy of the pack for your own
private server or single player. But I wont' support your subsequent issues
until it is removed from the pack.

Try Medieval Times, the new mod pack in the World of Dragons series that is
the closest to the vision I have in mind for it. That one has room for
something like colytra as it runs on a potato computer.
