### ISSUE TITLE
[please remove] Lava Dynamics

### ISSUE THREAD

**Issue by XanthusMaximus** [kreezxil/World-of-Dragons#216]
# Mod Nominated for Removal
Mod Name: Lava Dynamics

# Reason for Nomination

Reason: Causing huge lag and bugs with the server. Multiple issues of volcanos swallowing bases, appearing randomly around areas with tile entities, crashing the server due to conflictions with other mods, etc.

**Comment by kreezxil** [comment]
yeah around areas, i've switch it to worldgen only already, I'm not gonna
remove it.

Prove that is conflicting with other mods. Don't just say that.

**Comment by Warlok333** [comment]
There appears to be a conflict between Lava Dynamics and Stygian End (https://github.com/kreezxil/World-of-Dragons/issues/218). I don't mind the volcanoes spawning in new chunks, but perhaps the frequency could be turned down....a LOT. The landscape is hardly recognizable in many new areas because there are so many volcanoes spawning in chains of 10+ overlapping mounds.

**Comment by iamweirdie** [comment]
> There appears to be a conflict between Lava Dynamics and Stygian End (#218). I don't mind the volcanoes spawning in new chunks, but perhaps the frequency could be turned down....a LOT. The landscape is hardly recognizable in many new areas because there are so many volcanoes spawning in chains of 10+ overlapping mounds.

I suspected there might be similarities to Hell on Earth modpack, but not THIS much haha.

**Comment by kreezxil** [comment]
volcanos aren't suppose to be spawning in the end

**Comment by iamweirdie** [comment]
Please lower the number of volcanos spawning drastically. The volcano spawning so frequently is problematic because:

- it destroys general topside worldgen such as AW2 villages and magical forests,
- it kills mobs such as cockatrice and animania animals, and
- it blocks topside caves and ravines with lava.
