### ISSUE TITLE
[please remove] enchanting plus

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#237]
# Mod Nominated for Removal
Mod Name:Enchanting plus

# Reason for nomination
Reason:it makes all the enchants from apotheosis very easy to get even lvl 10 enchants

**Comment by Yodown814** [comment]
I disagree with your opinion on removing the mod "Enchanting Plus", because from what you are saying, "it makes all the enchants from apotheosis very easy to get even lvl 10 enchants", I don't see any necessary reason that we definitely should remove the mod. But, it does ruin some of the fun of the mod Apotheosis itself, so I will rather have Apotheosis enchantments to be **disable** from the Advanced Enchanting Table instead of removing the mod entirely.

**Comment by Draconian4466** [comment]
Thats what i said before but it seems like Kreezxil didnt see it

**Comment by kreezxil** [comment]
removed
