### ISSUE TITLE
[please remove] Dynamic Volcanoes. 

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#261]
From current observations i only see this mod being a drain on the server.
I do not understand the point or function of so many spawning volcanoes. 
They cause an issue of spawning on the block the player is standing on during chunk generation or the rng of whats in a chunk.  They also create quite a bit of lag when you are traveling at fast speeds. And the final issue i have is the location of the spawns. When a player is maintaining position for long enough you will end up with a near perfect circle of volcanoes. It can make traveling or transforming the land quite a pain.

Would like to hear someone with more experience on this mod put a bit of input in as i don't actually have much. This is just from observations i've made. 

-Sj

**Comment by Yodown814** [comment]
I strongly agree with what IppSwitch said. It's like there's nearly nowhere that can be a good place to build something big and nice, they are just **TOO** many (When you have a nice house on the land, and when you looked around, there's like 5 volcanoes around you). Plus, if aw2 got removed, there's gonna 0 good base structure that players could just move in (like what I personally did), so to dig a house is probably the best choice for a player to do since there are dragons on the top of your head. Lag on chunkload, ugly topography, plus there's even a lava dynamic mod, it's just too bad!!

**Comment by kreezxil** [comment]
No, there's an update in the pipeline that resolves issues that you've noticed.
