### ISSUE TITLE
[please add] Cosmetic armor reworked

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#263]
# Mod Nominated for Adding*
Mod Name:
Mod Link:https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

# Reason for Nomination
Reason: it adds armor for people to wear cosmeticly also people have been using for wearing cool armor like thaum robes and heads and ive been using it to wear dragon armor cosmeticly also allows you to hide your armor so you can just have your skin Also would work pretty well with roots which im pretty sure the armor isnt to good but people seem to like its looks

**Comment by DaredEnemyKilla** [comment]
I used it this mod almost from the second I joined the pack. It allowed me to remove my helmet from being shown at all which I liked a lot.

**Comment by Don-Silver** [comment]
This mod is purely aesthetic, and adds a lot of fun. It allows for personal expression without the unecessarily excessive, time consuming chisel and bits armour.

**Comment by NyanCatKrazy** [comment]
I love this mod!! and since roots is being added I can wear the roots armor on and be safe in a better armor that doesn't show! Please keep!

**Comment by Yodown814** [comment]
From my perspective, this mod is great at all sides, and it can also be helpful for players to hide their original looking that they might hated to a nice cosmetic armor that they loved. I used the old cosmetic armor mod before on wod17, and it worked very nicely. It reached the effect that I wanted, in comparison to my original big fat Tinker's armors.

**Comment by kreezxil** [comment]
and yet the new server lags ballz, are we gonna add everything we've become
crack addicted too? I'm not going to reconsider anything until we've worked
out the lag issues.

**Comment by kreezxil** [comment]
I'd like to see 5 other player chime in

**Comment by TheQuantumRuby** [comment]
Return it. I love the mod!

**Comment by Nb286** [comment]
the mod is amazing please put it back in

**Comment by iamweirdie** [comment]
i liked my forestry glasses as a cosmetic, i dont want them as a helmet and i dont wanna chisel a version of them. i also used leather yellow armor as my cosmetic previously, and they're terrible as actual armor, so that's why i'd like the cosmetic armor in please.

i also still think we went overboard with chopping out mods but that's a different matter.

**Comment by Nb286** [comment]
i love this mod becuase it alows people to ware cool armor that doesnt give very much armor but they can also ware good armor that has alot of armor points but doesnt look as cool

**Comment by kreezxil** [comment]
I don't want ditto style comments, i want actual reasons, actual short
stories. If you can't describe in some level of detail why this mod should
come back then that tells me you aren't using it at all and  you just came
here do a ditto on behalf of @draconian4466

**Comment by kreezxil** [comment]
maybe writing is too much to expect from everyone.

The lesson to be learned here is don't be offering to kill mods simply because you do not use them. I do not use comsetic armor reworked therefore using the @Draconian4466's standards no one else used it either.

Also you can't base the "no one" concept on the paltry amount of logins that the main server gets. There are 10,000+ other players of the pack that are not represented in the Discord nor in the Official Servers. There is no way to know if they are using the mod or not.

This does lend itself to an interesting mod to make. One that gave stats as to how much a mod is being used and have that uploaded to a server.
