### ISSUE TITLE
[feature request] Disable Drop on Death

### ISSUE THREAD

**Issue by Yodown814** [kreezxil/World-of-Dragons#264]
Since the removal of Corail Tombstone, players now will drop **all their items** on death, and it can be very terrible in some situations like dying under a dragon; before Corail Tombstone was removed, it was fine because upon death the mod gives you a special effect which prevents nearby mobs from seeing you which now we don't. So now whenever you do /back, if there's like 10 thousand mobs around you or you were killed by a super strong mob that doesn't leave, it's basically over. 

**Describe a solution you'd like to have**
Very easy and simple, type /gamerule keepInventory true

**Describe alternatives you've considered**
An alternative mod for this kind of problem like Corail Tombstone, but since you guys removed it, I couldn't find a better one to replace it, but I'm sure there's some on CurseForge(maybe??).

**Additional context**
I did this suggestion because I was tired of dying under a dragon who literally just sit right on top of my death spot and doesn't seem to be leaving, so **please**, please do consider about this, thank you ...

**Comment by kreezxil** [comment]
all grave and tombstone mods break immersion, you are not meant to solo dragons. you need to plan your attack carefully. In single player you can add that mod if you so desire. I want to see stories of players banding together to take down a dragon. Not how someone repeatedly tried 18 times because a tombstone allowed them to suffer no loss other than time.
