### ISSUE TITLE
[please fix] silver block to diamond visual

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#281]
When i put a block of silver from thermal foundation into the tinker's construct crafting station, the end result looks like 64 diamonds but when pulled, it turns into 9 thermal foundation silver ingots.

![image](https://user-images.githubusercontent.com/34356883/61570816-f9ae6f00-aa43-11e9-84b7-7fd6c65eda25.png)

**To Reproduce**
1. place a thermal foundation block of silver into the tinker's construct crafting station.
2. it will look like the image above.
3. attempt to extract the 64 diamonds
4. get bamboozled when you see 9 silver ingots from thermal foundation come out

**Versions:**

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Mod Pack : 18.3.213
- Mod Name and Version: 
    - Tinker's Construct 1.12.2-2.12.0.157, Thermal Foundation 2.6.3.27

**Comment by kreezxil** [comment]
@iamweirdie when making these reports, if you happen to cross post them
anywhere else, please come back here and link them in as it helps create a
chain of support. In short it allows other parties including developers to
track back thru and see what else has been affected and if any solutions
have been made.

**Comment by kreezxil** [comment]
finding this issue is a job for another day,

**Comment by kreezxil** [comment]
another thing that can cause this issue is when players update using MULTIMC such that they don't copy in the scripts folder causing client to server recipe desync.

I'm going to close it, and if it returns, make sure the pack is completely uninstalled and install it fresh in it's entirety. Then see if it continues and if it does then make a report.
