### ISSUE TITLE
[please add] Deep Mob Learning Mod

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#288]
![image](https://user-images.githubusercontent.com/34356883/61689954-10bbbe00-acdd-11e9-81de-95cf0fc300bb.png)
Well, evidently these 2 like it.

https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning

I know we said "no more mods" but I bring this particular mod up because a certain somebody on our server has continued to build a mob farm despite the fact that mob farms can't be turned off and are unfriendly to the servers. In comes this solution, DML, or Deep Mob Learning.

The mod advertises itself as a way to provide mob drops without spawning in the mobs. At first, this may sound overpowered. However, upon closer inspection, the mod still requires players to put in effort acquiring the necessary building blocks. As the player fights a targeted mob more and more, the DML "learns" more about the mob, until the system can finally start pumping out the mob drops.

While DML cannot eliminate players from building old-fashioned mob farms, it provides players with a server-friendly alternative and thus alleviating server resources from the old mob farms.

**FULL DISCLAIMER: I have not personally played with this mod, this description was through research and secondhand reviews.**

**Comment by IppSwitch** [comment]
I just have to chime in and say that I've been shown that it is possible to DEACTIVATE a spawner. From all the LagGoggles scans i have done, they have never generated tick while in this state. Aside from that, 

When watching the videos i think this is a very nice change from the standard mob farm that i have been introduced too. They are lazy, easy to make, and can end up being far to easy to abuse. I know this because i have my own mob farm. Albeit not as boosted as some players. I would love to test this and see how effective it might be.

**Comment by Draconian4466** [comment]
I have used this mod before. It makes it so you have to kill those mobs to level up the thing which makes it so you can get mob drops. Has cool trial things you have to do. Will require alot of solar panels because they use alot of rf so its not easy to have multiple

**Comment by kreezxil** [comment]
hmm, we'll give it a shot and I'll bring back that mod that makes spawners die off after so many mobs are generated.
