### ISSUE TITLE
[please fix] Fuel Input Machine not working (from Tinker's I/O)

### ISSUE THREAD

**Issue by migmolrod** [kreezxil/World-of-Dragons#304]
**Describe the bug**
The Fuel Input Machine from the Tinkers I/O mod doesn't seem to work. When you try to interact with it, all it says is "Lack of solid fuel" and it doesn't process any kind of fuel from any mod whatsoever.

**To Reproduce**
1. Craft a Fuel Input Machine
2. Put the Fuel Input Machine in your Smeltery from Tinker's mod
3. Open the Fuel Input Machine interface with right click (you may need to wait a second til it's recognized as part of the smeltery)
4. The message "Lack of solid fuel" appears and it doesn't work, no matter what fuel you put in there (bucket of lava, bit o' heats, coals... not even the Tinker's I/O fuel, called "Solid fuel")

**Screenshots**
https://imgur.com/a/3b9fbID

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack: World of Dragons 18.6.216
 - Mod Name: Tinker's I/O
 - Mod Version: tinker_io-1.12.2-rw2.7.1 (2.7.1 I assume?)

**Logs**
There is no crash

**Additional context**
n/a

**Comment by kreezxil** [comment]
I hear that, the image on the TINKERS IO home page tho while showing a recipe for solid fuel, only shows coal blocks in the TINKERS IO FUEL INPUT MACHINE. I suspect this might be a bug there.

**Comment by migmolrod** [comment]
I've tried coal, charcoal, block of coal, block of charcoal... nothing works.

**Comment by kreezxil** [comment]
resolved by removing the mod. Honestly it's probably a mod conflict, however, since WOD needs to go on a bit of a diet, might as well remove this mostly useless mod.

Case in point. 

At a certain point you can get a magma crucible from thermal expansion, and feed the output of in to one of the lava tanks for your smeltery. As for powering the magma crucible you can put tech reborn's ultimate solar panel on it and then feed all the excess cobble you've been generating to the crucible. Now you have an endless supply of lava for your smeltery that has less than 10 milliseconds per tick lag per part in the chain.
