### ISSUE TITLE
[please add] carry on or similar

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#351]
note to self: test to make sure you can set w/e mod you go with to not allow carrying boss mobs or hostiles for that matter.

**Comment by hellwolf95** [comment]
carry on already has a blacklist for certain things like ender dragons and wither but it also does not stop players from picking up unreasonable things such as waystones signs without adding them to the list and i think also chest in claimed chunks can be picked up since its not a right or left-click (needs to be tested).

**Comment by kreezxil** [comment]
what happened that you are no longer on discord?

**Comment by kreezxil** [comment]
so carryon is out, there are others to choose from.

**Comment by kreezxil** [comment]
added **Get in the Bucket mod** from https://www.curseforge.com/minecraft/mc-mods/get-in-the-bucket-mod

which only allows carrying vanilla mobs, it does have a mechanism for added modded mobs. so this fits what I want.
