### ISSUE TITLE
Thaumcraft Void Armor Not Infusing

### ISSUE THREAD

**Issue by eliotmanny** [kreezxil/World-of-Dragons#352]
Describe the bug
After creating my first piece of Void Thaumaturge Robes (the headpiece) I was unable to infuse a second piece (the chest plate).

1. Create and prepare an infusion altar
2. Place the recipe for any void thaumaturge armor in along with needed essentia and infuse
3. Repeat for another piece of void thaumaturge armor

Versions:

 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2847
 - Mod Pack: 19.7.232
 - Mod Name: Thaumcraft 6
 - Mod Version: Thaumcraft-1.12.2-6.1.BETA26

Additional context
This was on my own server and was replicated in a single player world with the Void Thaumaturge Chest plate and was unable to make another piece.

**Comment by kreezxil** [comment]
thank you for your report, however, Azanor has abandoned his project and the team that was suppose to take over has done nothing with it. As seen by the image below he hasn't done anything with mod since Novemember 2018. The only recourse is to remove Thaumcraft.

![image](https://user-images.githubusercontent.com/3880072/67297766-f9dd6100-f4af-11e9-863a-d3f22e3eaa7c.png)

You can further see here that there at least 200 open issues. https://github.com/Azanor/thaumcraft-beta/issues
