### ISSUE TITLE
Weather problem（always locked on Thunderstorm）

### ISSUE THREAD

**Issue by SaltedPanda** [kreezxil/World-of-Dragons#367]
[latest.log](https://github.com/kreezxil/World-of-Dragons/files/3964892/latest.log)
While I was playing， the weather always raining and with thunder. It makes my game frame count very low. I play it on single.

**Comment by kreezxil** [comment]
How is your pack is on **Forge 2836**?

```
[08:56:54] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2836 for Minecraft 1.12.2 loading
[08:56:54] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_201
```
That is lines 3 and 4 from the latest log. I am using **Forge 2847** for the pack, so that doesn't even agree with my pack at all.

Also, shouldn't matter, but your java is outdated by at least 20 subversions.

Further, what version of the pack are you running? You should be on the latest
![image](https://user-images.githubusercontent.com/3880072/70862698-343e0a00-1f05-11ea-94f5-e40688eee30e.png)

I can't support you if you're on one of the versions from in history, I can only agree that you are having an issue. To fix your issue would upset the version stream for the pack. I would have to make a whole new pack and have you change to it.

Also, the current version of the pack doesn't have Aroma1997core in it, **so** I have to ask, are you sure it is the World of Dragon pack?

# And thank you for thinking it is my pack, i really do appreciate that, this line, tells me you are 
on the **Dungeons, Dragons, and Space Shuttles** pack.
```
[08:57:02] [main/INFO] [FML]: Searching G:\MultiMC\instances\DDSS-6.3\minecraft\mods for mods
```
Which means you've reported to the wrong pack author.

The link you need is https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues
