### ISSUE TITLE
Weather problem（always locked on Thunderstorm）

### ISSUE THREAD

**Issue by SaltedPanda** [kreezxil/World-of-Dragons#368]
While I was playing， the weather always raining and with thunder. It makes my game frame count very low. I play it on single.
[latest.log](https://github.com/kreezxil/World-of-Dragons/files/3966119/latest.log)
I'm sorry,my mistake.I upload the wrong file.
I had added some other mods on your packs, but all what I've added are all auxiliary mods.
This is the right file.

**Comment by kreezxil** [comment]
Need you to get used to using a pasting service like 
- https://pastebin.com
- https://paste.ubuntu.com
- https://gist.github.com

you enter the file with the text copy all of it, goto one of those sites and paste all that data into the giant text boxes and hit submit, the page will refresh and give you a new url, copy that url and put it here. 

This helps everyone trying to help you in debugging efforts as we don't have to do 2 to 3 extra steps, we can click the link and the file appears in our browsers.

**Comment by kreezxil** [comment]
You're in luck because in this pack is wonderful tool called **LagGoggles**. It's not something you craft and it's always available.

Simply hit your INSERT key to get started. If you want to identify sources of FPS (frames per second) lag, then do an FPS scan, if you want to identify sources of TPS (ticks per second) lag, then do a world scan. If you're OP you'll get WORLD results for the entire world and not just your local rendering area.

I recommend doing a scan for 30 seconds, 60 seconds would be better. But if there are loads of players on, 10 or less would be better.

https://www.curseforge.com/minecraft/mc-mods/laggoggles

https://youtu.be/2ALrIvw1S4I

I know you think it's the weather.

Also just reread your opening statement and based on your logfile I felt like you were talking on a server, gui-newchat, not one of the mods in my pack.

# I have to suggest
remove every mod you added and see if the issue of weather being always on remains, I suspect it will not which means the problem is one of the mods you added. Things just got harder as you have to find the mod doing it and report to its author.

**Comment by kreezxil** [comment]
super stale, you had a xmas holiday to make the report be proper.
