### ISSUE TITLE
several mods out dated for server

### ISSUE THREAD

**Issue by Ariany231** [kreezxil/World-of-Dragons#372]
I tried to use the 1.12.2 MC version on my Sticky piston server but only get message that sereral mods are outdated.

**Comment by kreezxil** [comment]
you know it's ok for mods to be outdated in a pack.

but sounds like to me that you are reporting that your client and the
server are not matching.

the solution there is to make sure that both your server pack and the
client pack are on the same version of the pack. it's not enough to be on
the same minecraft version such as 1.7.10, 1.8, 1.9.4, 1.10.2, 1.11.2,
1.12.2, 1.14.4, or 1.15.1 but the part coming after that needs to match
too.Since you're posting on this issue tracker I'm going to assume that you
have client version 19.19.244 that means your server also needs the same
pack that was built for that client version.

And if you're really only talking about mod versions, dude ... please, i'm
not gonna update a mod just because it is outdated. I have a ton of packs,
I know what I'm doing (see
https://www.curseforge.com/members/kreezxil/projects).

But because you think I don't know what I'm doing, here is the dev cycle on
the most popular of my packs.

The actually cycle starts on Sunday (Update all the packs in the top 8) and
maybe Update again on Thursday if enough mods updated. Also the cycle will
fluctuate based on real bug reports.
Now for what I do during the cycle update.
1. update the mod on both client and server
2. after everything is updated, start the server to see what crashes
3. report crashes and roll the mod back to the previous version on both
server and client (this is why you see outdated mods on the day of the
cycle) any other times you see them is because it's in between the cycles.
4. if the server boots without issue, run the client
5. if a mod crashes, report the mod, then roll it back to previous version
on both client and server.
6. once the client starts without issue, fire up the server
7. make sure the client can connect to the server.
8. additional testing as required by bug reports.
9. after all these pass package both the server and the client and
distribute via curseforge.
