### ISSUE TITLE
Unable to claim quests

### ISSUE THREAD

**Issue by DanielMB62** [kreezxil/World-of-Dragons#41]
after completing quests i cannot claim when clicking the button, but can after pressing the apple button i can,

**Comment by kreezxil** [comment]
please tell me which quests you can not complete

**Comment by kreezxil** [comment]
this is because you are unfamiliar with the ftb quests system.

When you craft the item in question or perform the task, when you click the icon, you can on left side hit submit button and on the right side you click the reward to be claimed to claim it.

Also in regards to the cauldron quest you have to construct the correct cauldron, the basic vanilla cauldron is not the cauldron you need to make.
