### ISSUE TITLE
[please fix] Crashing trying to enter on the server...

### ISSUE THREAD

**Issue by Picono435** [kreezxil/World-of-Dragons#420]
https://paste.dimdev.org/ipicipawap.mccrash

There's the crash report above it what happens. I was in a boat and puff...

![image](https://user-images.githubusercontent.com/57836766/78655895-847b1680-78be-11ea-9afa-9e9b61960321.png)

This happened to me at the second time that I click at Multiplayer:

https://paste.dimdev.org/semexuwecu.mccrash

![image](https://user-images.githubusercontent.com/57836766/78656033-b68c7880-78be-11ea-9342-b7942b3436c9.png)

**Comment by Tenmaver** [comment]
Seems like you run into OUT OF MEMORY error.
Your Minecraft client does not have enough RAM.
"java.lang.OutOfMemoryError"
Try increasing RAM to your WoD: https://github.com/kreezxil/World-of-Dragons/wiki/Assign-More-Ram
Wod Requires atleast 6gigs of ram to run, 8gigs are recommended see requirements: https://github.com/kreezxil/World-of-Dragons/wiki/Requirements

**Comment by Picono435** [comment]
Humm ok Ill try solve the problem...

**Comment by Onikage056** [comment]
If you have the RAM to spare, I'd recommend 7-8GB RAM. It covers most modpacks with no issue (There are rather insane ones that'd likely call for more.), and leaves enough for running Youtube in the background if you so desire.

**Comment by kreezxil** [comment]
btw, @Picono435 never post a screen shot of screen saying something has crashed for a screen that doesn't even remotely show what the crash is.

**however** good job on figuring out  you needed to give us the link to the crash report.

Also in the future, when you have discovered that your issue is resolved, don't wait for us to close your ticket, you come close it.

Cheers!

And thanks for the report, it was greatly appreciated it.
