### ISSUE TITLE
[please add] Astral sorcery

### ISSUE THREAD

**Issue by Valarunga** [kreezxil/World-of-Dragons#71]
# Mod Nominated for Adding*
Mod Name: Astral Sorcery
Mod Link: https://minecraft.curseforge.com/projects/astral-sorcery

# Reason for Nomination

Reason:
It seems like a really unique and exciting mod that could add some more "magic" in WoD, as it has been a lot of techy mods that have been added lately.

**Comment by kreezxil** [comment]
which mod would you like to see go if I add this? if add this, we'll lose a
lot of players, the pack is too big right now.

**Comment by Valarunga** [comment]
Maybe something like immersive railroading, as I can't really see a use for it

**Comment by kreezxil** [comment]
Do realize that when we beginning adding and removing mods WORLD CORRUPTION
will the likely result. Your base, our world spawn, and lot of other nasty
stuff will happen.

Let's get some people in here voting on this and or discussing this. Tell
the other players that agree with you to sound off. Btw, Astral Sorcery
works great in Single Player, but I have had very serious mixed reactions
to it in Multiplayer and I not referring to the players, I'm referring to
what it does to the server. It has a massive calculation it performs for
each player based on it's concept of what stars are in the sky, this
calculation causes lag that is worse than the lag caused by Giant Dragons
and Dinosaurs.

**Comment by kreezxil** [comment]
officially added
