### ISSUE TITLE
[please add] programable spells

### ISSUE THREAD

**Issue by kingslayer296** [kreezxil/World-of-Dragons#96]
Mod Name:Psi
Mod Link:https://ftb.gamepedia.com/Psi

it would add programable spells that you wouldn't have to get into thaum to have, while being more diverse and useful than thaum.

**Comment by Drakyl** [comment]
Thaum isn't just usefull for spells, but they aren't useless. Just not all usefull

**Comment by kreezxil** [comment]
So basically you wished the Harry Potter books were rewritten such that he
had the Book of Souls from the beginning instead of some stupid twig and
the word "petronum"?

it's got to be one or the other. We got abyssal craft, astral sorcery and
now thaumcraft, oh and botania. why another magic mod? we need to get rid
of at least two to add one more. I personally want to get rid of abyssal
craft but that will cause world corruption in ways you can't imagine, then
next up I want to get rid of botania because it has guaranteed lag issues,
but everyone really does use it. then I'd like to get rid of thaumcraft,
but it attracted lots of layers and people are really enjoying it.

Nope, please just use one of those magic mods and get into them, a little
work will make you feel more proud about the acocmplishment.
